---
- name: Userforge TSN manage users
  hosts: localhost
  connection: local
  become: yes


  vars_files:
    - users.yml

    
  tasks:
    - name: Manage users
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        generate_ssh_key: yes
        remove: yes
      loop: "{{ users }}"
